#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: python:3.8

pipelines:
  default:
    - step:
        name: Build Container
        caches:
          - pip
        script:
          - docker build -t mit/scrapper -t mit/scrapper:${BITBUCKET_COMMIT} .
          - pipe: atlassian/aws-ecr-push-image:1.4.1
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              AWS_DEFAULT_REGION: ${REGION}
              IMAGE_NAME: mit/scrapper
              TAGS: ${BITBUCKET_COMMIT}
        services:
          - docker